import React, { useEffect, useState } from 'react';
import { apiRequest } from '../utils/api.js';
import { useAuth } from '../context/AuthContext.jsx';
import { Plus, Send, Users, ClipboardList } from 'lucide-react';

export default function AlumniDashboard({ activeTab }) {
  const { user } = useAuth();
  const [members, setMembers] = useState([]);
  const [feedback, setFeedback] = useState('');
  const [form, setForm] = useState({ title:'', description:'', assignedTo:'', priority:'Medium', deadline:new Date(Date.now()+3*86400000).toISOString().slice(0,10) });
  useEffect(()=>{ apiRequest('/users').then(x=>setMembers(Array.isArray(x)?x.filter(u=>['cat_a','president'].includes(u.role)):[])).catch(console.error); },[]);
  if(activeTab !== 'alumni_assign') return <div className="glass-panel p-6 rounded-3xl"><h2 className="text-xl font-bold text-white">Alumni Workspace</h2><p className="text-sm text-slate-400 mt-2">Use the Dashboard to see upcoming work and events. From here you can directly assign work to the Core Team or President.</p></div>;
  const submit = async (e)=>{e.preventDefault(); try { const x=await apiRequest('/tasks','POST',form); setFeedback(`Task assigned to ${x.assignedToName}.`); setForm({title:'',description:'',assignedTo:'',priority:'Medium',deadline:new Date(Date.now()+3*86400000).toISOString().slice(0,10)}); } catch(err){setFeedback(err.message);} };
  return <div className="glass-panel p-6 rounded-3xl space-y-6"><div><h2 className="text-xl font-bold text-white flex items-center gap-2"><Send className="w-5 h-5 text-amber-300"/>Assign Work to Leadership</h2><p className="text-xs text-slate-400 mt-1">Alumni can directly assign a task to the President or Core Team.</p></div>{feedback&&<div className="p-3 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-300 text-sm">{feedback}</div>}<form onSubmit={submit} className="space-y-4"><input required placeholder="Task title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="w-full p-3 glass-input"/><textarea placeholder="Instructions / description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="w-full p-3 glass-input" rows="4"/><div><label className="block text-xs text-slate-400 mb-2">Assign to *</label><div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-56 overflow-y-auto pr-1">{members.map(m=><button type="button" key={m.id} onClick={()=>setForm({...form,assignedTo:m.id})} className={`text-left p-3 rounded-xl border ${form.assignedTo===m.id?'border-cyan-400 bg-cyan-500/10':'border-slate-800 bg-slate-900/60'}`}><div className="font-semibold text-white">{m.name}</div><div className="text-[11px] text-slate-500">{m.role==='president'?'President':'Core Team'} · {m.designation||'Team Member'}</div></button>)}</div></div><div className="grid grid-cols-2 gap-3"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="p-3 glass-input"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select><input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} className="p-3 glass-input"/></div><button disabled={!form.assignedTo} className="w-full py-3 rounded-xl bg-amber-500 hover:bg-amber-400 disabled:opacity-40 text-slate-950 font-extrabold flex items-center justify-center gap-2"><Plus className="w-4 h-4"/>Assign Task</button></form></div>;
}
